---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf: |
    server {

        listen 80;

        access_log /var/log/nginx/access-default.log main;
        error_log /var/log/nginx/error-default.log;

        error_page   500 502 503 504  /50x.html;

            location /  {
              root    /usr/share/nginx/html/;

            }
    }
