---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: website

commonLabels:
  app.kubernetes.io/part-of: website
  app.kubernetes.io/component: webserver
  app.kubernetes.io/name: nginx


resources:
  - configmap-nginx.yaml
  - service.yaml
  - deployment-nginx.yaml
