---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: centurion

resources:
  - PVC-centurion.yaml
  - Deployment-api.yaml
  - Deployment-worker.yaml
  - Service-api.yaml
  - CiliumNetworkPolicy-centurion-api.yaml
  - CiliumNetworkPolicy-centurion-ui.yaml
  - CiliumNetworkPolicy-centurion-worker.yaml


