---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namePrefix: nofusscomputing-


namespace: website


resources:
  - ../../base/


components:
  - ../../components/gitlab_runner/
  - ../../components/ingress/


secretGenerator:
  - name: gitlab-runner-token
    envs:
      - runner-registration-token.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true


replacements:
  - source:
      kind: Secret
      name: gitlab-runner-token
      fieldPath: metadata.name
    targets:
      - select:
          kind: Runner
          name: gitlab-runner
        fieldPaths:
          - spec.token
