---
# on: push    # yamllint disable-line rule:truthy
name: CI


on:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint ${PWD}/


  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: kubescape/github-action@main
        continue-on-error: true
        with:
          format: sarif
          outputFile: results
          # # Optional: Specify the Kubescape Portal credentials 
          # account: ${{secrets.KUBESCAPE_ACCOUNT}}
          # accessKey: ${{secrets.KUBESCAPE_ACCESS_KEY}}
          # server: ${{ vars.KUBESCAPE_SERVER }}
          # # Optional: Scan a specific path. Default will scan the whole repository
          # files: "examples/*.yaml"
      - name: Upload Kubescape scan results to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif


  kubescape-fix-pr-reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1

      - uses: kubescape/github-action@main
        with:
          # account: ${{secrets.KUBESCAPE_ACCOUNT}}
          # accessKey: ${{secrets.KUBESCAPE_ACCESS_KEY}}
          # server: ${{ vars.KUBESCAPE_SERVER }}
          # files: ${{ steps.changed-files.outputs.all_changed_files }}
          fixFiles: true
          format: "sarif"

      - name: PR Suggester according to SARIF file
        if: github.event_name == 'pull_request_target'
        uses: HollowMan6/sarif4reviewdog@v1.0.0
        with:
          file: 'results.sarif'
          level: warning
